### ISSUE TITLE
Learning to use Medienwiki: First Signup

### ISSUE THREAD

**Issue by jdittrich** [BauhausUniversity/MedienWiki#12]
From the point of teaching the Medienwiki students could be better informed about the sense and use of the Medienwiki. While usability improvements should ease the Medienwiki use, we could provide a "Getting Started Guide" or the like. Best would be to have it displayed on the (first) login, like many services do (e.g. github). 
1. Is this possible
2. Ideas and suggestions what might be important.

**Comment by audiocommander** [comment]
Getting started is super, and I appreciate the reference to github.com, as they did it really well.

Technical info:
The first login is really hard to determine and it makes things quite complicated.
There are three ways to add/inject/change infos on the MediaWiki:
1. Creating a page in the Wiki, eg. I don't see why something like the github home shouldn't be done on our MediaWiki home.
2. Many pages on the MediaWiki have MediaWiki:Something pages that can be edited. For example: MediaWiki:Createaccount (though sometimes it just provides the possibility to add a one-liner).
3. There's Special:AllMessages that can be edited.
4. It can be added to the Skin
5. And finally, if it shouldn't be skin-related, it can be added via an Extension

## 
1. to 3. are the preferred ways, 4. is good, 5. should be avoided if possible because this one can break MW on updates if not done right. So, forgetting the first login is a good idea.

**Comment by jdittrich** [comment]
So, an alternative to 1st login would be:

making it accessible like on the starting page (e.g. first time here? Questions?_getting started guide link_ )
If the user is not logged in the skin can show a "not signed up? Create an account" at this place too. 

We could as well link it on the user-Page: "This is your user page... see the _getting started guide_. The user can just delete the text, which might be a great tutorial thing as well. 

btw.: If we want to increase learning and want to show that users can edit their user pages, why not use the user pages for a tutorial? It is a great way to learn as nothing on the general wiki pages can break
